require("core.options")
require("core.keymaps")
require("plugins")
require("core.colorscheme")
require("plugins.lsp.cmp")
require("plugins.lsp.mason")
require("plugins.lsp.handlers")
require("plugins.utils.nvim-tree")
require("plugins.utils.telescope")
require("plugins.syntax.treesitter")
require("plugins.ui.bufferline")
require("plugins.ui.lualine")
require("plugins.ui.colorizer")

